services:
  - type: web
    name: solwash
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: GOOGLE_CLIENT_ID
        value: 783558082274-4siu1j2g360l4c4r6v328g9nprkun079.apps.googleusercontent.com
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
